################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
[en.params]
footer_content = "All content is reserved for use by BizKite LLC."
# copyright
copyright = "Copyright by BizKite LLC"



